[workspace]
resolver = "2"
members = [
    "crates/hadris-iso-cli",
    "crates/hadris-iso",
    "crates/hadris-common",
    "crates/hadris",
    "crates/hadris-io",
]
default-members = [
    "crates/hadris-iso-cli",
    "crates/hadris-iso",
    "crates/hadris-common",
    "crates/hadris",
]

[workspace.package]
version = "0.1.2"
edition = "2024"
authors = ["hxyulin"]
license = "MIT"
repository = "https://github.com/hxyulin/hadris"

[workspace.dependencies]
log = "0.4.26"
bytemuck = "1.22.0"
bitflags = "2.9.0"
static_assertions = "1.1.0"
criterion = "0.5.1"
thiserror = "2.0.12"
cfg-if = "1.0.0"
tempfile = "3.19.1"

hadris-io = { path = "crates/hadris-io", version = "0.1.2" }
hadris-iso = { path = "crates/hadris-iso", version = "0.1.2" }
hadris-common = { path = "crates/hadris-common", version = "0.1.2" }
