[workspace]
resolver = "2"
members = [
    #"crates/hadris",
    #"crates/hadris-cli",
    "crates/hadris-core",
    "crates/hadris-fat",
]
default-members = [
    #"crates/hadris",
    #"crates/hadris-cli",
    "crates/hadris-core",
    "crates/hadris-fat",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
authors = ["hxyulin"]
repository = "https://github.com/hxyulin/hadris"
homepage = "https://github.com/hxyulin/hadris"

[workspace.dependencies]
hadris-core = { path = "crates/hadris-core", version = "0.1.1", default-features = false }
hadris-fat = { path = "crates/hadris-fat", version = "0.1.1", default-features = false }
#hadris = { path = "crates/hadris", version = "0.1.1" }

chrono = { version = "0.4.39", default-features = false }
bitflags = "2.8.0"
thiserror = { version = "2.0.12", default-features = false }
