[workspace]
resolver = "3"
members = [
    "crates/core/*",
    "crates/block/*",
    "crates/optical/*",
    "crates/archive/*",
    "crates/tools/*",
    "examples/*",
]
default-members = [
    "crates/core/*",
    "crates/block/*",
    "crates/optical/*",
    "crates/archive/*",
    "crates/tools/*",
]

[workspace.package]
edition = "2024"
rust-version = "1.88.0"
authors = ["hxyulin"]
license = "MIT"
repository = "https://github.com/hxyulin/hadris"

[workspace.dependencies]
bytemuck = { version = "1.22.0", default-features = false }
zerocopy = { version = "0.8", default-features = false, features = ["derive"] }
bitflags = "2.9.0"
static_assertions = "1.1.0"
cfg-if = "1.0.0"
embedded-io = { version = "0.7", default-features = false }
embedded-io-async = { version = "0.7", default-features = false }
tempfile = "3.19.1"
tracing = "0.1.41"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
libc = "0.2"

# Internal crates
hadris-macros = { version = "3.0.0-rc.1", path = "crates/core/hadris-macros" }
hadris-io = { version = "3.0.0-rc.1", path = "crates/core/hadris-io", default-features = false }
hadris-fs = { version = "3.0.0-rc.1", path = "crates/core/hadris-fs", default-features = false }
hadris-common = { version = "3.0.0-rc.1", path = "crates/core/hadris-common", default-features = false }
hadris-storage = { version = "3.0.0-rc.1", path = "crates/core/hadris-storage", default-features = false }
hadris-fat = { version = "3.0.0-rc.1", path = "crates/block/hadris-fat", default-features = false }
hadris-fat-raw = { version = "0.1.0", path = "crates/block/hadris-fat-raw", default-features = false }
hadris-part = { version = "3.0.0-rc.1", path = "crates/block/hadris-part", default-features = false }
hadris-iso = { version = "3.0.0-rc.1", path = "crates/optical/hadris-iso", default-features = false }
hadris-udf = { version = "3.0.0-rc.1", path = "crates/optical/hadris-udf", default-features = false }
hadris-cpio = { version = "3.0.0-rc.1", path = "crates/archive/hadris-cpio", default-features = false }
hadris = { version = "3.0.0-rc.1", path = "crates/core/hadris", default-features = false }
hadris-ntfs = { version = "3.0.0-rc.1", path = "crates/block/hadris-ntfs", default-features = false }
