[package]
name = "hadris-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["std"]
alloc = []
std = ["alloc", "spin/std"]

[dependencies]
bitflags = { workspace = true }
spin = { version = "0.9.8" }
