#![cfg_attr(not(feature = "std"), no_std)]
#![allow(async_fn_in_trait)]
#![deny(missing_docs)]

//! APFS container and filesystem support for Hadris.
//!
//! This crate folds the useful pieces of the upstream `apfs-types`,
//! `apfs-core`, and derive-generated parsing model into one modular crate.
//! On-disk structures live in [`types`] and parsing is explicit, small, and
//! endian-aware rather than generated by a separate proc-macro crate.

#[cfg(any(feature = "alloc", feature = "std"))]
extern crate alloc;
#[cfg(feature = "std")]
extern crate std;

/// Error types returned by APFS readers and writers.
pub mod error;
pub mod types;

#[cfg(all(feature = "read", feature = "async"))]
pub mod r#async;
#[cfg(feature = "read")]
pub mod read;
#[cfg(all(feature = "read", feature = "sync"))]
pub mod sync;
#[cfg(feature = "write")]
pub mod write;

pub use error::{ApfsError, Result};
