[package]
name = "hadris-apfs"
version = "3.0.0-rc.1"
description = "An experimental, read-only APFS container and filesystem reader"
readme = "README.md"
keywords = ["apfs", "filesystem", "apple", "disk"]
categories = ["filesystem", "no-std"]
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["std", "read", "sync"]
std = ["alloc", "hadris-io/std", "hadris-storage/std", "hadris-fs/std"]
alloc = ["hadris-fs/alloc", "hadris-storage/alloc"]
read = []
sync = ["hadris-io/sync", "hadris-storage/sync", "hadris-fs/sync"]
async = ["hadris-io/async", "hadris-storage/async", "hadris-fs/async"]

[dependencies]
hadris-io.workspace = true
hadris-storage.workspace = true
hadris-fs.workspace = true
hadris-macros.workspace = true

[dev-dependencies]
hadris-fs = { workspace = true, features = ["contract"] }
