[package]
name = "hadris"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A filesystem library fully written in Rust"
license.workspace = true

[features]
default = ["fat", "write"]
fat = ["hadris-fat"]
write = ["hadris-fat/write"]

[dependencies]
hadris-core = { workspace = true }
hadris-fat = { workspace = true, optional = true }
