[package]
name = "hadris-cpio-raw"
version = "0.1.0"
description = "CPIO on-disk layouts and I/O-free codecs"
readme = "README.md"
keywords = ["cpio", "no-std", "parser"]
categories = ["no-std", "parser-implementations"]
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
