[package]
name = "hadris-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
hadris = { workspace = true }
