[package]
name = "hadris-cli"
readme = "README.md"
description = "A command-line interface for Hadris"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "hadris"
path = "src/main.rs"

[features]
default = []

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.29", features = ["derive"] }

hadris = { workspace = true }
