[package]
name = "hadris-common"
version = "2.4.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Internal types and functions shared by the Hadris crates; not for direct use"
readme = "README.md"
keywords = ["filesystem", "endian"]
categories = ["no-std", "filesystem"]
include = ["src/**/*", "Cargo.toml"]

[features]
default = ["bytemuck"]
bytemuck = ["dep:bytemuck"]

[dependencies]
bytemuck = { workspace = true, optional = true, features = ["derive"] }
zerocopy = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true, features = ["derive"] }
static_assertions.workspace = true
