[package]
name = "hadris-iso-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
simple_logger = "5.0.0"
log.workspace = true

hadris-iso.workspace = true
