[package]
name = "hadris-fat"
description = "A library for working with FAT32 file systems, a standalone crate included in the hadris project"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = ["read", "write", "lfn"]
alloc = ["hadris-core/alloc", "chrono/alloc"]
std = ["alloc", "hadris-core/std", "chrono/std", "chrono/clock"]
read = []
write = ["alloc", "read"]
lfn = []

[dependencies]
hadris-core = { workspace = true, default-features = false }

bitflags = { workspace = true }
bytemuck = { version = "1.21.0", default-features = false, features = [
    "derive",
] }
chrono = { version = "0.4.39", default-features = false }

[dev-dependencies]
pretty_assertions = "1.4.1"
static_assertions = "1.1.0"
