[package]
name = "hadris-example-partition-list"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
hadris-io = { workspace = true, features = ["std", "sync"] }
hadris-part = { workspace = true, features = ["std", "sync", "read"] }
