// @ts-check

const fs = require("node:fs");
const path = require("node:path");
const {themes: prismThemes} = require("prism-react-renderer");

const siteUrl = process.env.HADRIS_SITE_URL || "https://hxyulin.github.io";
const baseUrl = process.env.HADRIS_BASE_URL || "/hadris/";
const docsBranch = process.env.HADRIS_DOCS_BRANCH || "next";

// Released versions, newest first, generated by `npm run versions`.
const versionsFile = path.join(__dirname, "versions.json");
const released = fs.existsSync(versionsFile)
  ? JSON.parse(fs.readFileSync(versionsFile, "utf8"))
  : [];
const hasVersions = released.length > 0;

function currentLabel() {
  if (!hasVersions) return "Current";
  const manifest = fs.readFileSync(
    path.join(__dirname, "../crates/core/hadris/Cargo.toml"),
    "utf8",
  );
  const match = /^version\s*=\s*"(\d+)\.(\d+)\.\d+[^"]*"/m.exec(manifest);
  const series = match && `${match[1]}.${match[2]}`;
  if (!series || released.includes(series)) return "Next (unreleased)";
  return `${series} (unreleased)`;
}

const staticDirectories = ["static"];
if (fs.existsSync(path.join(__dirname, "versioned_static"))) {
  staticDirectories.push("versioned_static");
}

const config = {
  title: "Hadris",
  tagline: "The Rust storage stack",
  favicon: "img/favicon.svg",
  url: siteUrl,
  baseUrl,
  organizationName: "hxyulin",
  projectName: "hadris",
  onBrokenLinks: "throw",
  staticDirectories,
  markdown: {
    hooks: {
      onBrokenMarkdownLinks: "throw",
    },
  },
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },
  presets: [
    [
      "classic",
      {
        docs: {
          routeBasePath: "/",
          sidebarPath: require.resolve("./sidebars.js"),
          editUrl: ({version, docPath}) =>
            version === "current"
              ? `https://github.com/hxyulin/hadris/edit/${docsBranch}/website/docs/${docPath}`
              : undefined,
          lastVersion: hasVersions ? released[0] : "current",
          versions: {
            current: {
              label: currentLabel(),
              ...(hasVersions && {path: "next"}),
            },
          },
        },
        blog: false,
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      },
    ],
  ],
  themeConfig: {
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ["bash", "rust", "toml"],
    },
    navbar: {
      title: "Hadris",
      items: [
        {type: "doc", docId: "getting-started", label: "Get started", position: "left"},
        {type: "doc", docId: "guides/index", label: "Use cases", position: "left"},
        {type: "doc", docId: "crates", label: "Crates", position: "left"},
        {type: "docsVersionDropdown", position: "right"},
        {
          href: "https://docs.rs/hadris",
          label: "API docs",
          position: "right",
        },
        {
          href: "https://github.com/hxyulin/hadris",
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Documentation",
          items: [
            {label: "Get started", to: "/getting-started"},
            {label: "Use cases", to: "/guides"},
          ],
        },
        {
          title: "Project",
          items: [
            {label: "API docs", href: "https://docs.rs/hadris"},
            {label: "Crates.io", href: "https://crates.io/crates/hadris"},
            {label: "GitHub", href: "https://github.com/hxyulin/hadris"},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Hadris contributors. MIT licensed.`,
    },
  },
};

module.exports = config;
