FROM rust:1.88.0-bookworm

RUN rustup component add clippy rustfmt

RUN apt-get update \
    && apt-get install --yes --no-install-recommends fuse3 ntfs-3g \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
